Dependecy fixes, and MDX2
AxisCommunications/practical-react-components pull request #205
Opened 2022-02-24 13:05 UTC by Tigge

2022-03-01 11:20 UTC, anius commented on tsconfig.json
> +    "jsx": "react-jsx",
Will be resolved by #209

2022-03-07 16:12 UTC, Tigge commented on packages/core/package.json
> +    "react": "^17.0.0",
Reverted

2022-03-07 16:13 UTC, Tigge commented on packages/docs/src/mdx/Base.tsx
> +import React from 'react'
Very true, fixed

2022-03-08 09:54 UTC, anius requested changes

2022-03-08 09:54 UTC, anius commented on packages/docs/package.json
> +    "react": "^17.0.1",
Use exact version

2022-03-08 09:54 UTC, anius commented on packages/docs/package.json
> +    "react-dom": "^17.0.1",
Use exact version

2022-03-08 09:54 UTC, anius commented on packages/docs/package.json
> +    "react-is": "^17.0.1",
Use exact version

2022-03-08 09:54 UTC, anius commented on packages/docs/src/mdx/coreComponents/Button.mdx
> +```typescript type="live" test="woo"
So why not remove?

2022-03-08 09:54 UTC, anius commented on packages/docs/webpack.config.ts
> +      fallback: { url: false },
Add some comment why this is needed?

2022-03-08 09:54 UTC, anius commented on packages/ui-tests/package.json
> +    "react": "^17.0.1",
Use exact version

2022-03-08 09:54 UTC, anius commented on packages/ui-tests/package.json
> +    "react-dom": "^17.0.1",
Use exact version

2022-03-08 09:54 UTC, anius commented on packages/ui-tests/package.json
> +    "react-is": "^17.0.1",
Use exact version

2022-03-10 09:02 UTC, Therealnaxos approved these changes
"mob-reviewed", Zeno approves changes.

2022-04-20 08:30 UTC, anius commented
@Tigge I've moved your code to #220 as I couldn't update this PR.

2022-05-03 11:56 UTC, closed without merging