fix(tooltip): hide tooltip when touched outside of a component
AxisCommunications/practical-react-components pull request #277
Opened 2023-08-30 13:58 UTC by HitomiWin

Fixes: #276

### Describe your changes

Imported useClickOutside from 'react-hooks-shareable' and added it to onPointerDown event.

### Issue ticket number and link

- Fixes #276 

### Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have verified that the code builds perfectly fine on my local system
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have verified that my code follows the style already available in the repository
- [ ] I have made corresponding changes to the documentation

2023-08-30 14:28 UTC, danielkaxis commented
We break current behaviour with this implementation. On mobile devices when the user scrolls, the user could scroll for a small distance before the tooltip disappeared. The motivation for this was that when you are using a mobile device you touch the phone all the time and the tooltip would just disappear. We should discuss this further on how to do.

2023-08-31 06:24 UTC, HitomiWin commented
> We break current behaviour with this implementation. On mobile devices when the user scrolls, the user could scroll for a small distance before the tooltip disappeared. The motivation for this was that when you are using a mobile device you touch the phone all the time and the tooltip would just disappear. We should discuss this further on how to do.

See the comment [FTWEB-5607](https://jira.se.axis.com/browse/FTWEB-5607?focusedCommentId=2046793&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2046793)

I think it's ok to disappear soon the tooltip according to the definition of tooltip.

2023-09-26 06:55 UTC, danielkaxis requested changes

2023-09-26 06:55 UTC, danielkaxis commented on packages/ui-tests/src/coreComponents/Tooltip.spec.ts
> +    // Touch the swcreen again
:)

2023-09-26 07:05 UTC, HitomiWin commented on packages/ui-tests/src/coreComponents/Tooltip.spec.ts
> +    // Touch the swcreen again
sorry. fixed it.

2023-10-03 13:46 UTC, danielkaxis approved these changes

2023-10-03 13:46 UTC, merged